title: EduController
description: 教育用制御教材ポータル
lang: ja
timezone: Asia/Tokyo

theme: null
permalink: pretty

# ここは sitemap & canonical 用（リンク直書きでも必要）
url: "https://samizo-aitl.github.io"
baseurl: "/EduController"

markdown: kramdown
kramdown: { input: GFM }
math_engine: mathjax

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope: { path: "" }
    values: { layout: clean }
